# Middleware Specific Configurations
middleware:
  cors:
    allowed_origins: "*"
    allowed_headers: "Content-Type, Authorization"
    allowed_methods: "GET, POST, PUT, DELETE"

# Backing Services  Specific Configurations
backingServices:
  oracle.db:
    url: ""